name: Setup aarch64-linux-musl-cross
description: Download, install, and setup aarch64-linux-musl-cross to your path.
author: ahaoboy
branding:
  icon: play-circle
  color: white

runs:
  using: "composite"
  steps:
    - name: Setup musl aarch64
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          curl \
          libc6-arm64-cross \
          libc6-dev-arm64-cross \
          crossbuild-essential-arm64 \
          clang \
          qemu-system-arm \
          qemu-efi-aarch64 \
          qemu-utils \
          qemu-user

        curl -L https://github.com/ahaoboy/aarch64-linux-musl-cross-build/releases/latest/download/aarch64-linux-musl-cross.tgz | tar xzf -
        sudo mv aarch64-linux-musl-cross /musl

        echo "CC_aarch64_unknown_linux_musl=aarch64-linux-musl-gcc" >> $GITHUB_ENV
        echo "CXX_aarch64_unknown_linux_musl=aarch64-linux-musl-g++" >> $GITHUB_ENV
        echo "AR_aarch64_unknown_linux_musl=aarch64-linux-musl-ar" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-musl-gcc" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUNNER=qemu-aarch64" >> $GITHUB_ENV

        echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++" >> $GITHUB_ENV
        echo "AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUNNER=qemu-aarch64" >> $GITHUB_ENV

        echo "LD_LIBRARY_PATH=/usr/aarch64-linux-gnu/lib" >> $GITHUB_ENV

        sudo ln -s /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 /lib/ld-linux-aarch64.so.1

        mkdir -p ~/.cargo/
        echo "[target.aarch64-unknown-linux-musl]" >> ~/.cargo/config.toml
        echo 'rustflags = ["-C", "link-self-contained=yes","-C", "linker=rust-lld"]' >> ~/.cargo/config.toml
        echo "[target.aarch64-unknown-linux-gnu]" >> ~/.cargo/config.toml
        echo 'rustflags = ["-C", "linker=aarch64-linux-gnu-gcc"]' >> ~/.cargo/config.toml

        echo "/musl/bin" >> $GITHUB_PATH